version: '3'
volumes:
  postgres_data: {}

services:
  app:
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - .:/var/www/portfolio
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
