default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: 5
  host: db

development:
  <<: *default
  database: portfolio_development

production:
  <<: *default
  database: portfolio_production
